version: "2"
run:
  timeout: 5m

linters:
  default: none
  enable:
    - asciicheck
    - depguard
    - dupl
    - durationcheck
    - errname
    - errorlint
    - forbidigo
    - goconst
    - goheader
    - gomodguard_v2
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  settings:
    depguard:
      rules:
        non-tests:
          files:
            - "!$test"
            - "!**/*test/*.go"
          deny:
            - pkg: testing
            - pkg: github.com/stretchr/testify
    goheader:
      values:
        const:
          COMPANY: Splunk Inc.
      template: |-
        Copyright {{ COMPANY }}
        SPDX-License-Identifier: Apache-2.0
    goconst:
      ignore-tests: true
    gosec:
      excludes:
        - G404
    govet:
      disable:
        - composites
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
