name: ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: lycheeverse/lychee-action@v1.9.3
        with:
          fail: true

  make:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.6
    - uses: actions/setup-go@v5.0.0
      with:
        go-version: '1.22'
        check-latest: true
    - run: make ci

  compatibility-test:
    strategy:
      matrix:
        go-version:
        - '1.21'
        - '1.22'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.6
    - uses: actions/setup-go@v5.0.0
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
    - run: go test -race ./...
