name: ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  goyek:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.22'
          check-latest: true
      - run: ./goyek.sh -v ci
      # TODO: Uncomment after making the repository public.
      # - uses: codecov/codecov-action@v4.3.0
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     fail_ci_if_error: true
      #     file: ./coverage.out

  check-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: lycheeverse/lychee-action@v1.9.3
        with:
          fail: true

  compatibility-test:
    strategy:
      matrix:
        go-version:
        - '1.21'
        - '1.22'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.2
    - uses: actions/setup-go@v5.0.0
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
    - run: go test -race ./...
